Test API access and fail early

diff --git a/resources/bin/orchestrator-client b/resources/bin/orchestrator-client
--- a/resources/bin/orchestrator-client
+++ b/resources/bin/orchestrator-client
@@ -123,6 +123,11 @@ function get_curl_auth_params {
       requires_auth+=" --disallow-username-in-url"
   fi
 
+  # Test API access
+  curl "${basic_auth}" -s --head "${orchestrator_api}" 2>&1 | fgrep -q "401 Unauthorized" && \
+    echo "401 Unauthorized" && \
+    return
+
   echo "${requires_auth}"
 }
 
@@ -170,6 +175,10 @@ function detect_leader_api() {
   # or it may be a space delimited list, such as "http://host1:3000/api http://host2:3000/api http://host3:3000/api "
   # - in which case we figure out which of the URLs is the leader
   local curl_auth_params="$(get_curl_auth_params)"
+  
+  if [[ ${curl_auth_params} == "401 Unauthorized" ]]; then
+    fail "Cannot access orchestrator at ${orchestrator_api}.  Check ORCHESTRATOR_API is configured correctly and orchestrator is running"
+  fi
 
   leader_api=
   apis=($orchestrator_api)
@@ -203,12 +212,16 @@ function api() {
   set -o pipefail
 
   api_call_result=0
-  for sleep_time in 0.1 0.2 0.5 1 2 2.5 5 0 ; do
-    api_response=$(curl ${curl_auth_params} -s "$uri" | jq '.')
-    api_call_result=$?
-    [ $api_call_result -eq 0 ] && break
-    sleep $sleep_time
-  done
+  if [[ ${curl_auth_params} != "401 Unauthorized" ]]; then
+    for sleep_time in 0.1 0.2 0.5 1 2 2.5 5 0 ; do
+      api_response=$(curl ${curl_auth_params} -s "$uri" | jq '.')
+      api_call_result=$?
+      [ $api_call_result -eq 0 ] && break
+      sleep $sleep_time
+    done
+  else
+    api_call_result=1
+  fi
   if [ $api_call_result -ne 0 ] ; then
     fail "Cannot access orchestrator at ${leader_api}.  Check ORCHESTRATOR_API is configured correctly and orchestrator is running"
   fi
