Expect and use go1.14

diff --git a/script/ensure-go-installed b/script/ensure-go-installed
--- a/script/ensure-go-installed
+++ b/script/ensure-go-installed
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 PREFERRED_GO_VERSION=go1.12.6
-SUPPORTED_GO_VERSIONS='go1.1[234]'
+SUPPORTED_GO_VERSIONS='go1.1[2345]'
 
 GO_PKG_DARWIN=${PREFERRED_GO_VERSION}.darwin-amd64.pkg
 GO_PKG_DARWIN_SHA=ea78245e43de2996fa0973033064b33f48820cfe39f4f3c6e953040925cc5815
@@ -25,28 +25,12 @@ if [ -z "$(which go)" ] || [ -z "$(go version | grep "$SUPPORTED_GO_VERSIONS")" 
   export PATH="$GOROOT/bin:$PATH"
 fi
 
-# Check if local install exists, and install otherwise.
+# Fail if correct go version still unfound
 if [ -z "$(which go)" ] || [ -z "$(go version | grep "$SUPPORTED_GO_VERSIONS")" ]; then
-  [ -d "$GODIR" ] && rm -rf $GODIR
-  mkdir -p "$GODIR"
-  cd "$GODIR";
-
-  if [ $(uname -s) = "Darwin" ]; then
-    curl -L -O https://dl.google.com/go/$GO_PKG_DARWIN
-    shasum -a256 $GO_PKG_DARWIN | grep $GO_PKG_DARWIN_SHA
-    xar -xf $GO_PKG_DARWIN
-    cpio -i < com.googlecode.go.pkg/Payload
-  else
-    curl -L -O https://dl.google.com/go/$GO_PKG_LINUX
-    shasum -a256 $GO_PKG_LINUX | grep $GO_PKG_LINUX_SHA
-    tar xf $GO_PKG_LINUX
-  fi
-
-  # Prove we did something right
-  echo "$(go version) installed in $GODIR: Go Binary: $(which go)"
-else
-  echo "$(go version) found in $GODIR: Go Binary: $(which go)"
+  exit 1
 fi
+
+echo "$(go version) found in $GODIR: Go Binary: $(which go)"
 
 cd $ROOTDIR
 
