more debug info

diff --git a/tests/system/deploy-replication b/tests/system/deploy-replication
--- a/tests/system/deploy-replication
+++ b/tests/system/deploy-replication
@@ -15,12 +15,14 @@ if ! test-refresh-connections ; then
   echo "ERROR refreshing connections"
   exit 1
 fi
+echo "# Discovering all instances"
 orchestrator-client -c all-instances | while read i ; do
-  test-retry orchestrator-client -c discover -i $i
+  test-retry orchestrator-client -c discover -i $i || echo "+ ERROR discovering $i"
 done
-orchestrator-client -c submit-masters-to-kv-stores
-test-retry bash -c 'sleep 1 ; orchestrator-client -c which-replicas -i 127.0.0.1:10111 | wc -l | grep 3'
-orchestrator-client -c submit-masters-to-kv-stores
+orchestrator-client -c submit-masters-to-kv-stores | egrep ':.*:'
+echo "# Validating replicas"
+test-retry bash -c 'sleep 2 ; orchestrator-client -c which-replicas -i 127.0.0.1:10111 | wc -l | grep -q 3' || echo "+ ERROR validating replicas"
+orchestrator-client -c submit-masters-to-kv-stores | egrep ':.*:'
 
 (cd orchestrator-ci-env && script/run-heartbeat >> $deploy_replication_file 2>&1)
 sleep 2
