postpone heartbeat restart until after KV has been submitted

diff --git a/tests/system/deploy-replication b/tests/system/deploy-replication
--- a/tests/system/deploy-replication
+++ b/tests/system/deploy-replication
@@ -8,12 +8,6 @@ fi
 
 echo "# Redeploying replication"
 (cd orchestrator-ci-env && script/deploy-replication > $deploy_replication_file 2>&1)
-(cd orchestrator-ci-env && script/run-heartbeat >> $deploy_replication_file 2>&1)
-
-if ! mysql -uci -pci -h 127.0.0.1 --port=10111 -s -s -e "select * from test.heartbeat" | grep -q . ; then
-  echo "ERROR: cannot read heartbeat value"
-  exit 1
-fi
 
 # orchestrator's cached connections will have been invalid now. Force refresh by
 # probing all instances:
@@ -24,3 +18,9 @@ fi
 orchestrator-client -c submit-masters-to-kv-stores
 sleep 5
 orchestrator-client -c submit-masters-to-kv-stores
+
+(cd orchestrator-ci-env && script/run-heartbeat >> $deploy_replication_file 2>&1)
+if ! mysql -uci -pci -h 127.0.0.1 --port=10111 -s -s -e "select * from test.heartbeat" | grep -q . ; then
+  echo "ERROR: cannot read heartbeat value"
+  exit 1
+fi
